### PR TITLE
Update rknpu 0.9.8-noble

### PR DESCRIPTION
**Pull request by darkice9x**
Download the file from https://github.com/airockchip/rknn-llm/blob/main/rknpu-driver/rknpu_driver_0.9.8_20241009.tar.bz2
Extract the archive. 
To comment out the specific line in linux-rockchip/drivers/rknpu/rknpu_devfreq.c at line 237 
/* .set_soc_info = rockchip_opp_set_low_length, */

### CODE REVIEW

**Comment by darkice9x** [comment]
There are new files in the armbian linux kernel, so please refer to them.

**Comment by platima** [comment]
So what happened here? I've just installed the latest 24.04 but it only has 0.9.7. Has me a tad stumped!

**Comment by darkice9x** [comment]
> So what happened here? I've just installed the latest 24.04 but it only has 0.9.7. Has me a tad stumped!

This is the last version I've built, and it only works on the Orange Pi 5 and Pi 5 Plus. It looks like there won't be any more upgrades. I recommend using Armbian. That's all for now.

refer to https://github.com/darkice9x/ubuntu-rockchip-modified/releases/tag/master

**Comment by platima** [comment]
> > So what happened here? I've just installed the latest 24.04 but it only has 0.9.7. Has me a tad stumped!
> 
> This is the last version I've built, and it only works on the Orange Pi 5 and Pi 5 Plus. It looks like there won't be any more upgrades. I recommend using Armbian. That's all for now.
> 
> refer to https://github.com/darkice9x/ubuntu-rockchip-modified/releases/tag/master

Ah damn. Thanks for that info. I had actually looked at Armbian, but could not find any images that had both working NPU and GPU.

Any idea on how to get 0.9.8 working in an existing image? I've not worked with driver compilation in a VERY long time (nearly 20 years haha), so I'm a tad rusty. Especially when it comes to this sort of thing!

Thanks either way.

**Comment by darkice9x** [comment]
@platima 
The latest Armbian supports both NPU and GPU. OpenGLES 1.1, 2.0, and 3.2, OpenCL up to 2.2 and Vulkan 1.2, etc.

**Comment by platima** [comment]
> @platima The latest Armbian supports both NPU and GPU. OpenGLES 1.1, 2.0, and 3.2, OpenCL up to 2.2 and Vulkan 1.2, etc.

Ah thanks for that - I'm running on the Sige7, so community maintained. I might need to build an image myself! That being said, it has kernel 6.18 which is amazing as it should include all the merges in 6.17 for RKNN/RKNPU from what I recall.

I had previously tried Armbian_25.2.2_Rock-5-itx_bookworm_current_6.12.15_cinnamon-backported-mesa_desktop.img.xz as the latest that said it had some support when I was first setting up the docker host. Alas, the hardware was faulty hence moving to Sige7

**Pull request closed without merging**
