### PR TITLE
Kernel 6.1 - Support Raspberry Pi V1 and V2 Cameras

### PR DESCRIPTION
**Pull request by peyton-howe**
- Add working kernel drivers for Raspberry Pi V1 (ov5647) and v2 (imx219) cameras. Source code from [radxa kernel](https://github.com/radxa/kernel/blob/linux-6.1-stan-rkr1/drivers/media/i2c).
- Make ov5647 and imx219 camera drivers built-in
- Make ad5398 lens driver built-in
- Add Orange Pi 5 overlays for the V1 and V2 cameras for each camera slot

### CODE REVIEW

**Comment by Joshua-Riek** [comment]
Is the ov5647 and imx219 camera overlays specific to the Orange Pi 5? Or can they be used on any RK3588 board?

**Comment by peyton-howe** [comment]
Specific to the Orange Pi 5 boards. Radxa already has their V2 camera overlays for the [5a](https://github.com/Joshua-Riek/linux-rockchip/blob/linux-6.1-stan-rkr1/arch/arm64/boot/dts/rockchip/overlay/rock-5a-rpi-camera-v2.dts), [5b](https://github.com/Joshua-Riek/linux-rockchip/blob/linux-6.1-stan-rkr1/arch/arm64/boot/dts/rockchip/overlay/rock-5b-rpi-camera-v2.dts), [cm5](https://github.com/Joshua-Riek/linux-rockchip/blob/linux-6.1-stan-rkr1/arch/arm64/boot/dts/rockchip/overlay/radxa-cm5-io-rpi-camera-v2.dts), and nx5 io slot [0](https://github.com/Joshua-Riek/linux-rockchip/blob/linux-6.1-stan-rkr1/arch/arm64/boot/dts/rockchip/overlay/radxa-nx5-io-rpi-camera-v2-cam0.dts) and [1](https://github.com/Joshua-Riek/linux-rockchip/blob/linux-6.1-stan-rkr1/arch/arm64/boot/dts/rockchip/overlay/radxa-nx5-io-rpi-camera-v2-cam1.dts) merged in. The rock 5B seems to have a similar format with a [general camera overlay](https://github.com/Joshua-Riek/linux-rockchip/blob/linux-6.1-stan-rkr1/arch/arm64/boot/dts/rockchip/rk3588-rock-5b-camera.dtsi) and camera specific overlays in the /overlay folder.

**Comment by Joshua-Riek** [comment]
Hmm then maybe rename the overlays to start with `orangepi-5` as it's specific to the Orange Pi 5 board such as `orangepi-5-imx219-c3.dtbo`.

**Comment by peyton-howe** [comment]
The latest commit renames all Orange Pi 5 specific camera overlays from the rk3588-{camera name}-{camera port} format to orangepi-5-{camera name}-{camera port} format.

**Pull request closed without merging**
