### PR TITLE
Add DTS files for Firefly AIO-3588L

### PR DESCRIPTION
**Pull request by serwansj**
I copied over the device tree files for the AIO-3588L board from the Firefly kernel source (https://gitlab.com/firefly-linux)

### CODE REVIEW

**Comment by serwansj** [comment]
see also https://github.com/Joshua-Riek/ubuntu-rockchip/issues/930

**Comment by Joshua-Riek** [comment]
Please clean up the device tree, this is absolutely terrible. 

- Remove dependency on rk3588-firefly-port.dtsi and rk3588-diff.dtsi
- Squash rk3588-aio-3588l.dts, aio-3588l.dtsi, rk3588-firefly-demo.dtsi into rk3588-aio-3588l.dts
- Remove chosen node

**Comment by serwansj** [comment]
@Joshua-Riek i tried to clean it up following your suggestions, hope it is acceptable now. 

regarding chosen node:  i had to include this, otherwise, the board would not boot and would throw the error i mentioned to in the issue

**Comment by serwansj** [comment]
@Joshua-Riek i tried to clean it up following your suggestions, hope it is acceptable now.

regarding chosen node: i had to include this, otherwise, the board would not boot and would throw the error i mentioned to in the issue

**Comment by Joshua-Riek** [comment]
Thanks for cleaning this up, looks good

**Pull request merged**
