### PR TITLE
arm64: dts: rockchip: add rk3588s Embedfire LubanCat-4

### PR DESCRIPTION
**Pull request by erd-yunmu**

### CODE REVIEW

**Comment by Joshua-Riek** [comment]
I'd like to have all reasonable kernel changes done via a PR sent to Armbian's repo with the mindset of an Armbian user, as it is their kernel repo for their distro. I believe It's better to contribute to one centralized repo instead of having a whole bunch of forks, but I also want to respect that the kernel is for Armbian and its users. The code looks good and should have no issue being merged.

This repo primarily has my packaging for the Launchpad PPA, WiFi drivers, and the kernel defconfig.

**Comment by erd-yunmu** [comment]
Ok, I will close it first, and I will find time to pr to armbian later

**Comment by Joshua-Riek** [comment]
Also, if you are interested, we can add the LubanCat 4 and 5 to the ubuntu-rockchip repo. I do not have the hardware, but I assume you can test it to ensure it works. It should be easy to add the boards, will only need the device tree added to the kernel, and add the packaging for u-boot which I can do if pointed to the u-boot repo.

**Comment by erd-yunmu** [comment]
I feel ok, I will prepare to sort it out and merge it into ubuntu-rockchip

**Pull request closed without merging**
